[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [ "*.js", "*.json", ]

[formatter.shfmt]
command = "shfmt"
options = ["--language-dialect", "bash", "--write",]
includes = [".envrc",]

[formatter.nix]
command = "bash"
options = [
    "-euc",
    """
deadnix --edit "$@"

# statix doesn't support passing multiple files yet:
# https://github.com/nerdypepper/statix/issues/69
for file in "$@"; do
  statix fix "$file"
  statix check "$file"
done

alejandra "$@"
    """,
    "--",
]
includes = [ "*.nix" ]

[formatter.just]
command = "just"
options = ["--unstable", "--fmt", "--justfile",]
includes = [".justfile",]
